# Generated by Django 5.1.6 on 2025-11-13 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="in_comparisons", to="products.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Comparison",
                "verbose_name_plural": "Product Comparisons",
                "db_table": "product_comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrowsingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for anonymous users",
                        max_length=40,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Time spent viewing in seconds"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, help_text="Where the user came from", max_length=255
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browsing_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Browsing History",
                "verbose_name_plural": "Browsing Histories",
                "db_table": "browsing_history",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-viewed_at"],
                        name="browsing_hi_user_id_4bf1b8_idx",
                    ),
                    models.Index(
                        fields=["session_key", "-viewed_at"],
                        name="browsing_hi_session_f46315_idx",
                    ),
                    models.Index(
                        fields=["product", "-viewed_at"],
                        name="browsing_hi_product_4cbc13_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for anonymous users",
                        max_length=40,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        db_index=True, help_text="Search query text", max_length=255
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(default=0, help_text="Number of results found"),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters applied (price, category, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the search (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "db_table": "search_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_quer_user_id_486cee_idx",
                    ),
                    models.Index(
                        fields=["query", "-created_at"],
                        name="search_quer_query_1bea7d_idx",
                    ),
                ],
            },
        ),
    ]
