# Generated by Django 5.1.6 on 2025-11-13 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_coupon_code_order_discount_amount_and_more"),
        ("products", "0002_productcomparison_browsinghistory_searchquery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique coupon code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description of the coupon"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("fixed", "Fixed Amount Discount"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum order value to apply coupon",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount (for percentage coupons)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Total usage limit (null = unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.IntegerField(
                        default=1,
                        help_text="Usage limit per user",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(default=0, help_text="Current number of uses"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Coupon valid from this date",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(help_text="Coupon valid until this date"),
                ),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=False,
                        help_text="Only for users with no previous orders",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Is this coupon active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific users (empty = all users)",
                        related_name="exclusive_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apply only to these categories (empty = all)",
                        related_name="coupons",
                        to="products.category",
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apply only to these products (empty = all)",
                        related_name="coupons",
                        to="products.product",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual discount applied",
                        max_digits=10,
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="orders.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Usage",
                "verbose_name_plural": "Coupon Usages",
                "db_table": "coupon_usages",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["code", "is_active"], name="coupons_code_e67bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="coupons_valid_f_8ea39f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["coupon", "user"], name="coupon_usag_coupon__4d4fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(fields=["order"], name="coupon_usag_order_i_7b9192_idx"),
        ),
    ]
