# Generated by Django 5.1.6 on 2025-11-24 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_coupon_couponusage_coupon_coupons_code_e67bf2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Net amount after fees (EGP)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_summary",
            field=models.JSONField(
                blank=True, default=dict, help_text="Payment summary details (JSON)"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Platform fee (EGP)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Processing fee (EGP)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shipmenttracking",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("confirmed", "Confirmed"),
                    ("on_pack", "On Pack"),
                    ("dispatched", "Dispatched"),
                    ("out_to_delivery", "Out to Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="ordered",
                help_text="Current shipment status",
                max_length=50,
            ),
        ),
    ]
