# Generated by Django 5.1.6 on 2025-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin approval status - seller can only operate if approved",
            ),
        ),
    ]
