# Generated by Django 5.1.6 on 2025-11-24 21:29

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sellerprofile_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Egypt", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default shipping address"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Address label, e.g., Home, Work",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Address",
                "verbose_name_plural": "Shipping Addresses",
                "db_table": "shipping_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="business_description",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="verified_seller",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="approval_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when seller was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_address",
            field=models.TextField(blank=True, help_text="Business physical address"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_email",
            field=models.EmailField(
                blank=True,
                help_text="Business email (can differ from user email)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Business phone number",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_registration_number",
            field=models.CharField(
                blank=True,
                help_text="Business registration/license number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Business verified (documents checked)"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_name",
            field=models.CharField(help_text="Official business name", max_length=255),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="is_approved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Seller account approved by admin",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Average seller rating",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="total_orders",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of orders"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerprofile",
            index=models.Index(
                fields=["is_approved"], name="seller_prof_is_appr_37d180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerprofile",
            index=models.Index(
                fields=["business_name"], name="seller_prof_busines_718435_idx"
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="shippingaddress",
            index=models.Index(
                fields=["user", "is_default"], name="shipping_ad_user_id_30adcf_idx"
            ),
        ),
    ]
