# Generated by Django 5.1.6 on 2025-11-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cart",
            new_name="shopping_ca_user_id_eab8ae_idx",
            old_name="carts_user_id_b1c689_idx",
        ),
        migrations.RenameIndex(
            model_name="cart",
            new_name="shopping_ca_session_bf3e83_idx",
            old_name="carts_session_2c783d_idx",
        ),
        migrations.RenameIndex(
            model_name="cart",
            new_name="shopping_ca_updated_d8c159_idx",
            old_name="carts_updated_d6666c_idx",
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="shopping_ca_cart_id_cb053c_idx",
            old_name="cart_items_cart_id_421c1e_idx",
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="shopping_ca_added_a_b2289b_idx",
            old_name="cart_items_added_a_a7c525_idx",
        ),
        migrations.AlterModelTable(
            name="cart",
            table="shopping_carts",
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="shopping_cart_items",
        ),
    ]
