# Generated by Django 5.1.6 on 2025-11-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reward_account",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "points_balance",
                    models.IntegerField(
                        default=0, help_text="Current available points"
                    ),
                ),
                (
                    "total_earned",
                    models.IntegerField(
                        default=0, help_text="Total points earned (lifetime)"
                    ),
                ),
                (
                    "total_spent",
                    models.IntegerField(
                        default=0, help_text="Total points redeemed (lifetime)"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        help_text="Reward tier based on activity",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reward Account",
                "verbose_name_plural": "Reward Accounts",
                "db_table": "reward_accounts",
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Points Earned"),
                            ("redeemed", "Points Redeemed"),
                            ("bonus", "Bonus Points"),
                            ("referral", "Referral Bonus"),
                            ("expired", "Points Expired"),
                            ("adjustment", "Manual Adjustment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Points amount (+ for earned, - for redeemed)"
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="Points balance after this transaction"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Transaction description", max_length=500
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When these points expire (if applicable)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Points Transaction",
                "verbose_name_plural": "Points Transactions",
                "db_table": "points_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="points_tran_user_id_c020a4_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="points_tran_transac_5a1292_idx",
                    ),
                    models.Index(
                        fields=["order"], name="points_tran_order_i_58fb58_idx"
                    ),
                ],
            },
        ),
    ]
