# Generated by Django 5.1.6 on 2025-11-24 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productcomparison_browsinghistory_searchquery"),
        ("rewards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Reward name (e.g., "50 EGP Discount Voucher")',
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the reward"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("discount_voucher", "Discount Voucher"),
                            ("free_shipping", "Free Shipping"),
                            ("free_product", "Free Product"),
                            ("vip_service", "VIP Service"),
                            ("charity", "Charity Donation"),
                            ("early_access", "Early Access"),
                            ("custom", "Custom Reward"),
                        ],
                        default="discount_voucher",
                        max_length=50,
                    ),
                ),
                (
                    "points_required",
                    models.PositiveIntegerField(
                        help_text="Points required to redeem this reward"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount amount in EGP (for voucher rewards)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "charity_name",
                    models.CharField(
                        blank=True,
                        help_text="Charity organization name (for charity donations)",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="gift",
                        help_text="Font Awesome icon name (without fa- prefix)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reward is currently available",
                    ),
                ),
                (
                    "is_limited_time",
                    models.BooleanField(
                        default=False, help_text="Whether this is a limited-time reward"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this reward becomes available",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="When this reward expires", null=True
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this can be redeemed (total)",
                        null=True,
                    ),
                ),
                (
                    "redemption_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this reward has been redeemed",
                    ),
                ),
                (
                    "tier_required",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        help_text="Minimum tier required to redeem",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "free_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product to give for free (for product rewards)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_products",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "db_table": "rewards",
                "ordering": ["display_order", "points_required"],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_spent",
                    models.PositiveIntegerField(
                        help_text="Points spent on this redemption"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="Generated coupon code for this redemption",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for this redemption",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="rewards.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Redemption",
                "verbose_name_plural": "Reward Redemptions",
                "db_table": "reward_redemptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLoginReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_date",
                    models.DateField(db_index=True, help_text="Date of login"),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=10, help_text="Points earned for this login"
                    ),
                ),
                (
                    "streak_day",
                    models.PositiveIntegerField(
                        default=1, help_text="Current streak day (1-7+)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_login_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Login Reward",
                "verbose_name_plural": "Daily Login Rewards",
                "db_table": "daily_login_rewards",
                "ordering": ["-login_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_date"],
                        name="daily_login_user_id_a99fb9_idx",
                    )
                ],
                "unique_together": {("user", "login_date")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("points_earned", "Points Earned"),
                            ("tier_upgrade", "Tier Upgrade"),
                            ("points_expiring", "Points Expiring"),
                            ("reward_redeemed", "Reward Redeemed"),
                            ("points_gift_received", "Points Gift Received"),
                            ("promotion", "Promotion"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Optional link (URL or route name)",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the notification",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_c4e471_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Number of points to gift"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message to recipient"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_gifts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Points Gift",
                "verbose_name_plural": "Points Gifts",
                "db_table": "points_gifts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="points_gift_sender__c2bb13_idx",
                    ),
                    models.Index(
                        fields=["recipient", "status"],
                        name="points_gift_recipie_464df4_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(
                fields=["is_active", "display_order"], name="rewards_is_acti_746724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(
                fields=["reward_type"], name="rewards_reward__3e8a29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(
                fields=["user", "-created_at"], name="reward_rede_user_id_5d0af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(fields=["status"], name="reward_rede_status_9fab25_idx"),
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(
                fields=["reward"], name="reward_rede_reward__ba8cc4_idx"
            ),
        ),
    ]
