# Generated by Django 5.1.6 on 2025-11-24 13:03

from django.db import migrations
from decimal import Decimal


def create_default_rewards(apps, schema_editor):
    Reward = apps.get_model("rewards", "Reward")

    default_rewards = [
        {
            "name": "50 EGP Discount Voucher",
            "description": "Get 50 EGP off your next purchase",
            "reward_type": "discount_voucher",
            "points_required": 500,
            "discount_amount": Decimal("50.00"),
            "icon": "gift",
            "tier_required": "bronze",
            "display_order": 1,
        },
        {
            "name": "100 EGP Discount Voucher",
            "description": "Get 100 EGP off your next purchase",
            "reward_type": "discount_voucher",
            "points_required": 1000,
            "discount_amount": Decimal("100.00"),
            "icon": "gift",
            "tier_required": "bronze",
            "display_order": 2,
        },
        {
            "name": "200 EGP Discount Voucher",
            "description": "Get 200 EGP off your next purchase",
            "reward_type": "discount_voucher",
            "points_required": 2000,
            "discount_amount": Decimal("200.00"),
            "icon": "gift",
            "tier_required": "silver",
            "display_order": 3,
        },
        {
            "name": "Free Shipping",
            "description": "Get free shipping on your next order",
            "reward_type": "free_shipping",
            "points_required": 300,
            "icon": "truck",
            "tier_required": "bronze",
            "display_order": 4,
        },
        {
            "name": "VIP Customer Support",
            "description": "Enjoy 24/7 priority customer support for 1 month",
            "reward_type": "vip_service",
            "points_required": 1500,
            "icon": "headset",
            "tier_required": "silver",
            "display_order": 5,
        },
        {
            "name": "Early Access to Sales",
            "description": "Get 24-hour early access to upcoming sales",
            "reward_type": "early_access",
            "points_required": 800,
            "icon": "clock",
            "tier_required": "bronze",
            "display_order": 6,
        },
    ]

    for data in default_rewards:
        Reward.objects.get_or_create(
            name=data["name"],
            defaults={
                "description": data["description"],
                "reward_type": data["reward_type"],
                "points_required": data["points_required"],
                "discount_amount": data.get("discount_amount"),
                "icon": data["icon"],
                "tier_required": data["tier_required"],
                "display_order": data["display_order"],
                "is_active": True,
            },
        )


def delete_default_rewards(apps, schema_editor):
    Reward = apps.get_model("rewards", "Reward")
    reward_names = [
        "50 EGP Discount Voucher",
        "100 EGP Discount Voucher",
        "200 EGP Discount Voucher",
        "Free Shipping",
        "VIP Customer Support",
        "Early Access to Sales",
    ]
    Reward.objects.filter(name__in=reward_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_reward_rewardredemption_dailyloginreward_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_rewards, delete_default_rewards),
    ]
