# Generated by Django 5.1.6 on 2025-11-04 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TryonSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique session identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Session metadata (device, browser, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tryon_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Try-On Session",
                "verbose_name_plural": "Try-On Sessions",
                "db_table": "tryon_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TryonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        help_text="User uploaded photo",
                        upload_to="vto/user_photos/%Y/%m/%d/",
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        help_text="Result image with product overlay",
                        null=True,
                        upload_to="vto/results/%Y/%m/%d/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "face_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Face detection landmarks and data",
                    ),
                ),
                (
                    "auto_delete_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to auto-delete for privacy (GDPR compliance)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tryon_images",
                        to="products.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="virtual_tryon.tryonsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Try-On Image",
                "verbose_name_plural": "Try-On Images",
                "db_table": "tryon_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VTOAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("glasses", "Glasses/Eyewear"),
                            ("hat", "Hat/Headwear"),
                            ("mask", "Face Mask"),
                            ("jewelry", "Jewelry"),
                            ("accessory", "Accessory"),
                        ],
                        db_index=True,
                        help_text="Type of VTO asset",
                        max_length=20,
                    ),
                ),
                (
                    "overlay_image",
                    models.ImageField(
                        help_text="Transparent PNG overlay image",
                        upload_to="vto/overlays/%Y/%m/",
                    ),
                ),
                (
                    "anchor_points",
                    models.JSONField(
                        default=dict, help_text="Anchor points for positioning (JSON)"
                    ),
                ),
                (
                    "scale_factor",
                    models.FloatField(
                        default=1.0, help_text="Scale factor for overlay size"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional VTO configuration (JSON)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this VTO asset active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this VTO asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vto_assets",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "VTO Asset",
                "verbose_name_plural": "VTO Assets",
                "db_table": "vto_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["user", "-created_at"], name="tryon_sessi_user_id_ef8f98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["session_id"], name="tryon_sessi_session_eca763_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonimage",
            index=models.Index(
                fields=["session", "-created_at"], name="tryon_image_session_050f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonimage",
            index=models.Index(
                fields=["product"], name="tryon_image_product_63ba9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonimage",
            index=models.Index(fields=["status"], name="tryon_image_status_26b76f_idx"),
        ),
        migrations.AddIndex(
            model_name="tryonimage",
            index=models.Index(
                fields=["auto_delete_at"], name="tryon_image_auto_de_acd034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vtoasset",
            index=models.Index(
                fields=["product", "is_active"], name="vto_assets_product_5fa997_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vtoasset",
            index=models.Index(
                fields=["asset_type"], name="vto_assets_asset_t_f1d10d_idx"
            ),
        ),
    ]
