# Generated by Django 5.1.6 on 2025-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_tryon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vtoasset",
            name="placement_mode",
            field=models.CharField(
                choices=[
                    ("face", "Face Detection"),
                    ("room", "Room Placement"),
                    ("auto", "Auto-Detect"),
                ],
                default="auto",
                help_text="VTO placement mode: face detection or room placement",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vtoasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("glasses", "Glasses/Eyewear"),
                    ("hat", "Hat/Headwear"),
                    ("mask", "Face Mask"),
                    ("jewelry", "Jewelry"),
                    ("accessory", "Accessory"),
                    ("room", "Room/Placement"),
                ],
                db_index=True,
                help_text="Type of VTO asset",
                max_length=20,
            ),
        ),
    ]
