# Generated by Django 5.1.6 on 2025-11-04 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "AI Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        help_text="Who sent this message",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional message data (product IDs, links, etc.)",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="AI model used (e.g., gemini-2.5-flash)",
                        max_length=50,
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of tokens used for this message",
                        null=True,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="AI response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="Was this message helpful? (user feedback)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatFeedback",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="feedback",
                        serialize=False,
                        to="ai_chatbot.chatmessage",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("incorrect", "Incorrect Information"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Detailed feedback from user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Feedback",
                "verbose_name_plural": "Chat Feedback",
                "db_table": "chat_feedback",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique session identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Chat session title (auto-generated from first message)",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Session metadata (user preferences, context, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Is session active?"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_chatbot.chatsession",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-last_activity"], name="chat_sessio_user_id_2eee2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_id"], name="chat_sessio_session_a3bcba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["is_active", "-last_activity"],
                name="chat_sessio_is_acti_d11b7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_597c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="chat_messag_role_ddd811_idx"),
        ),
    ]
