# Generated by Django 5.1.6 on 2025-11-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chatbot", "0001_initial"),
        ("products", "0002_productcomparison_browsinghistory_searchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="External identifier (e.g., ASIN) used in the dataset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "highlights",
                    models.JSONField(
                        blank=True, default=list, help_text="Key bullet points/features"
                    ),
                ),
                (
                    "review_snippets",
                    models.JSONField(
                        blank=True, default=list, help_text="Short review quotes"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average rating from dataset (0-5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price information if available",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Dataset file this record came from",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to an internal catalog product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entries",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Knowledge Entry",
                "verbose_name_plural": "Product Knowledge Entries",
                "db_table": "chatbot_product_knowledge",
                "indexes": [
                    models.Index(
                        fields=["category"], name="chatbot_pro_categor_1b03c1_idx"
                    ),
                    models.Index(fields=["title"], name="chatbot_pro_title_246b8d_idx"),
                ],
            },
        ),
    ]
