# Generated by Django 5.1.6 on 2025-11-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Product View"),
                            ("add_to_cart", "Add to Cart"),
                            ("purchase", "Purchase"),
                            ("tryon", "Virtual Try-On"),
                            ("wishlist", "Add to Wishlist"),
                            ("review", "Product Review"),
                            ("search", "Search Query"),
                        ],
                        db_index=True,
                        help_text="Type of event/interaction",
                        max_length=20,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Session identifier for tracking user journey",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data (JSON)",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Browser user agent", max_length=500
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="User IP address (anonymized for GDPR compliance)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product involved in the event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for guests)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Event",
                "verbose_name_plural": "User Events",
                "db_table": "events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="events_user_id_e5338a_idx"
                    ),
                    models.Index(
                        fields=["product", "-timestamp"],
                        name="events_product_109361_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="events_event_t_55886d_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-timestamp"],
                        name="events_session_035c11_idx",
                    ),
                ],
            },
        ),
    ]
