# Generated by Django 5.1.6 on 2025-11-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_invoice_paymenttransaction"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific order item for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="orders.orderitem",
            ),
        ),
    ]
